/*
 * exporters.js — the current design as files other tools open.
 *
 *   toIFC(p, results)      IFC4 building model (ISO 10303-21 text): site, building,
 *                          storey; floor slab, roof slab and walls; one element per
 *                          rack row segment; dock doors; staging and cross-aisle spaces;
 *                          and the design's parameters and key results as property sets.
 *                          Every solid is a rectangle extruded upwards, in metres.
 *   toDXF(p, results)      the floor plan as AutoCAD R12 DXF (lines and text on
 *                          named layers), in metres.
 *   freecadCommand(p, d)   the freecadcmd line that regenerates this exact design as a
 *                          real FreeCAD model (only parameters that differ from defaults).
 *
 * Geometry comes from calculations.js (rows, bays, doors), like the 3D view and the
 * plan. Pure: window.WH.exporters in the browser, module.exports in Node.
 */
(function (root, factory) {
  if (typeof module !== "undefined" && module.exports) module.exports = factory(require("./calculations.js"));
  else { root.WH = root.WH || {}; root.WH.exporters = factory(root.WH.calc); }
})(typeof self !== "undefined" ? self : this, function (calc) {
  "use strict";

  // ------------------------------------------------------------------ IFC
  // IFC GlobalIds are 128-bit values written in a 22-character base-64 form.
  const B64 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_$";
  function ifcGuid(seed, i) {
    // deterministic 128 bits from (seed, i): four rounds of a 32-bit mix
    const bytes = [];
    let h = (seed ^ Math.imul(i + 1, 0x9e3779b1)) >>> 0;
    for (let k = 0; k < 4; k++) {
      h = Math.imul(h ^ (h >>> 16), 0x85ebca6b) >>> 0; h = Math.imul(h ^ (h >>> 13), 0xc2b2ae35) >>> 0; h = (h ^ (h >>> 16) ^ (k * 0x27d4eb2f)) >>> 0;
      bytes.push((h >>> 24) & 255, (h >>> 16) & 255, (h >>> 8) & 255, h & 255);
    }
    bytes[6] = (bytes[6] & 0x0f) | 0x40; bytes[8] = (bytes[8] & 0x3f) | 0x80;   // shaped like a v4 UUID
    // 2 bits, then 21 groups of 6 bits
    let bits = "";
    bytes.forEach(function (b) { bits += b.toString(2).padStart(8, "0"); });
    let out = B64[parseInt(bits.slice(0, 2), 2)];
    for (let k = 2; k < 128; k += 6) out += B64[parseInt(bits.slice(k, k + 6), 2)];
    return out;
  }
  function str(s) { return "'" + String(s).replace(/\\/g, "\\\\").replace(/'/g, "''").replace(/[^\x20-\x7e]/g, function (c) { return "\\X2\\" + c.charCodeAt(0).toString(16).toUpperCase().padStart(4, "0") + "\\X0\\"; }) + "'"; }
  function num(v) { const s = (+v).toFixed(6).replace(/0+$/, ""); return s.endsWith(".") ? s + "0" : s; }

  function toIFC(p, results, meta) {
    meta = meta || {};
    const L = results.layout, cap = results.capacity, D = calc.doorSets(p);
    const WT = p.wall_thickness / 1000, WL = p.warehouse_length, WW = p.warehouse_width, CH = p.clear_height;
    const lines = [];
    let id = 0, guidN = 0;
    const seed = 0x5eed ^ Math.round(WL * 100) ^ Math.round(WW * 1000);
    const add = function (s) { id++; lines.push("#" + id + "=" + s + ";"); return "#" + id; };
    const guid = function () { return str(ifcGuid(seed, guidN++)); };

    // units, contexts, project
    const origin = add("IFCCARTESIANPOINT((0.,0.,0.))");
    const zDir = add("IFCDIRECTION((0.,0.,1.))"), xDir = add("IFCDIRECTION((1.,0.,0.))");
    const worldAxes = add("IFCAXIS2PLACEMENT3D(" + origin + "," + zDir + "," + xDir + ")");
    const ctx = add("IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.E-05," + worldAxes + ",$)");
    const body = add("IFCGEOMETRICREPRESENTATIONSUBCONTEXT('Body','Model',*,*,*,*," + ctx + ",$,.MODEL_VIEW.,$)");
    const uLen = add("IFCSIUNIT(*,.LENGTHUNIT.,$,.METRE.)"), uArea = add("IFCSIUNIT(*,.AREAUNIT.,$,.SQUARE_METRE.)");
    const uVol = add("IFCSIUNIT(*,.VOLUMEUNIT.,$,.CUBIC_METRE.)"), uAng = add("IFCSIUNIT(*,.PLANEANGLEUNIT.,$,.RADIAN.)");
    const units = add("IFCUNITASSIGNMENT((" + [uLen, uArea, uVol, uAng].join(",") + "))");
    const project = add("IFCPROJECT(" + guid() + ",$," + str(meta.name || "Warehouse Model") + "," + str("Generated by Warehouse Model " + (meta.version || "") + " (kathuman)") + ",$,$,$,(" + ctx + ")," + units + ")");

    // spatial structure: site ▸ building ▸ ground-floor storey, all at the origin
    const place = function (rel, x, y, z) {
      const pt = add("IFCCARTESIANPOINT((" + num(x) + "," + num(y) + "," + num(z) + "))");
      return add("IFCLOCALPLACEMENT(" + (rel || "$") + "," + add("IFCAXIS2PLACEMENT3D(" + pt + ",$,$)") + ")");
    };
    const sitePl = place(null, 0, 0, 0), bldPl = place(sitePl, 0, 0, 0), stPl = place(bldPl, 0, 0, 0);
    const site = add("IFCSITE(" + guid() + ",$,'Site',$,$," + sitePl + ",$,$,.ELEMENT.,$,$,$,$,$)");
    const building = add("IFCBUILDING(" + guid() + ",$," + str(meta.name || "Warehouse") + ",$,$," + bldPl + ",$,$,.ELEMENT.,$,$,$)");
    const storey = add("IFCBUILDINGSTOREY(" + guid() + ",$,'Ground floor',$,$," + stPl + ",$,$,.ELEMENT.,0.)");
    add("IFCRELAGGREGATES(" + guid() + ",$,$,$," + project + ",(" + site + "))");
    add("IFCRELAGGREGATES(" + guid() + ",$,$,$," + site + ",(" + building + "))");
    add("IFCRELAGGREGATES(" + guid() + ",$,$,$," + building + ",(" + storey + "))");

    // a box: rectangle (w along x, d along y) at corner (x, y, z), extruded h upwards
    const boxShape = function (w, d, h) {
      const c = add("IFCCARTESIANPOINT((" + num(w / 2) + "," + num(d / 2) + "))");
      const prof = add("IFCRECTANGLEPROFILEDEF(.AREA.,$," + add("IFCAXIS2PLACEMENT2D(" + c + ",$)") + "," + num(w) + "," + num(d) + ")");
      const solid = add("IFCEXTRUDEDAREASOLID(" + prof + "," + worldAxes + "," + zDir + "," + num(h) + ")");
      const rep = add("IFCSHAPEREPRESENTATION(" + body + ",'Body','SweptSolid',(" + solid + "))");
      return add("IFCPRODUCTDEFINITIONSHAPE($,$,(" + rep + "))");
    };
    const contained = [], spaces = [], psetFor = [];
    const element = function (type, name, x, y, z, w, d, h, tail, objType) {
      const e = add(type + "(" + guid() + ",$," + str(name) + ",$," + (objType ? str(objType) : "$") + "," + place(stPl, x, y, z) + "," + boxShape(w, d, h) + "," + tail + ")");
      contained.push(e);
      return e;
    };

    // structure
    element("IFCSLAB", "Floor slab", -WT, -WT, -0.2, WL + 2 * WT, WW + 2 * WT, 0.2, "$,.FLOOR.");
    element("IFCSLAB", "Roof", -WT, -WT, CH, WL + 2 * WT, WW + 2 * WT, 0.3, "$,.ROOF.");
    element("IFCWALL", "West wall (receiving" + (D.u ? " and shipping" : "") + ")", -WT, 0, 0, WT, WW, CH, "$,.SOLIDWALL.");
    element("IFCWALL", "East wall" + (D.u ? "" : " (shipping)"), WL, 0, 0, WT, WW, CH, "$,.SOLIDWALL.");
    element("IFCWALL", "South wall", -WT, -WT, 0, WL + 2 * WT, WT, CH, "$,.SOLIDWALL.");
    element("IFCWALL", "North wall", -WT, WW, 0, WL + 2 * WT, WT, CH, "$,.SOLIDWALL.");

    // racks: one element per row per segment, with its own numbers
    const segs = L.segments.filter(function (sg) { return sg.bays > 0; });
    L.rows.forEach(function (row) {
      segs.forEach(function (sg) {
        const name = "Rack row " + row.index + (segs.length > 1 ? " segment " + (sg.index + 1) : "");
        const e = element("IFCFURNITURE", name, sg.x0, row.y, 0, sg.length, row.depth, p.rack_height + p.load_height, "$,.SHELF.", "Pallet rack: " + L.rackType.label);
        psetFor.push({ of: e, name: "Pset_WarehouseRack", props: [
          ["RackType", "IFCLABEL", L.rackType.label], ["Bays", "IFCINTEGER", sg.bays], ["Levels", "IFCINTEGER", p.levels_per_rack],
          ["PalletsDeep", "IFCINTEGER", L.rackType.deep], ["PalletPositions", "IFCINTEGER", sg.bays * cap.positionsPerBay],
          ["TopBeamHeight", "IFCLENGTHMEASURE", p.rack_height], ["BayWidth", "IFCLENGTHMEASURE", p.bay_width]] });
      });
    });

    // dock doors (thin panels in the wall line)
    const door = function (xWall, yc, name) {
      const w = p.dock_bay_width - 0.7;
      const e = add("IFCDOOR(" + guid() + ",$," + str(name) + ",$,$," + place(stPl, xWall, yc - w / 2, 0) + "," + boxShape(WT, w, 3.0) + ",$,3.," + num(w) + ",.GATE.,.ROLLINGUP.,$)");
      contained.push(e);
    };
    D.inY.forEach(function (y, i) { door(-WT, y, "Receiving dock " + (i + 1)); });
    D.outY.forEach(function (y, i) { door(D.u ? -WT : WL, y, "Shipping dock " + (i + 1)); });

    // spaces: staging zones and mid cross-aisles (thin volumes on the floor)
    const space = function (name, x, w) {
      const s = add("IFCSPACE(" + guid() + ",$," + str(name) + ",$,$," + place(stPl, x, 0, 0) + "," + boxShape(w, WW, 3.0) + ",$,.ELEMENT.,.INTERNAL.,$)");
      spaces.push(s);
    };
    space(D.u ? "Receiving and shipping staging" : "Receiving staging", 0, p.cross_aisle_width);
    space(D.u ? "End cross-aisle" : "Shipping staging", WL - p.cross_aisle_width, p.cross_aisle_width);
    for (let k = 0; k + 1 < L.segments.length; k++) space("Mid cross-aisle " + (k + 1), L.segments[k].x0 + L.segmentLength, p.mid_cross_aisle_width);

    add("IFCRELCONTAINEDINSPATIALSTRUCTURE(" + guid() + ",$,$,$,(" + contained.join(",") + ")," + storey + ")");
    if (spaces.length) add("IFCRELAGGREGATES(" + guid() + ",$,'Spaces',$," + storey + ",(" + spaces.join(",") + "))");

    // property sets: every input parameter and the key results on the building
    const val = function (type, v) { return type + "(" + (type === "IFCLABEL" ? str(v) : type === "IFCINTEGER" ? Math.round(v) : num(v)) + ")"; };
    const pset = function (of, name, props) {
      const ps = props.filter(function (pr) { return pr[2] !== undefined && pr[2] !== null && (pr[1] === "IFCLABEL" || isFinite(pr[2])); })
        .map(function (pr) { return add("IFCPROPERTYSINGLEVALUE(" + str(pr[0]) + ",$," + val(pr[1], pr[2]) + ",$)"); });
      const set = add("IFCPROPERTYSET(" + guid() + ",$," + str(name) + ",$,(" + ps.join(",") + "))");
      add("IFCRELDEFINESBYPROPERTIES(" + guid() + ",$,$,$,(" + of + ")," + set + ")");
    };
    const inputs = Object.keys(p).sort().map(function (k) { return [k, typeof p[k] === "string" ? "IFCLABEL" : "IFCREAL", p[k]]; });
    pset(building, "Pset_WarehouseModelInputs", inputs);
    pset(building, "Pset_WarehouseModelResults", [
      ["StoragePositions", "IFCINTEGER", cap.storageCapacity], ["PracticalCapacity", "IFCINTEGER", cap.practicalCapacity],
      ["RackRows", "IFCINTEGER", L.numRackRows], ["BaysPerRow", "IFCINTEGER", L.baysPerRow], ["Selectivity", "IFCREAL", cap.selectivity],
      ["SecondsPerPalletMove", "IFCREAL", results.travel.perMove], ["LiftTrucks", "IFCINTEGER", results.travel.forkliftsNeeded],
      ["PeakTruckWaitMinutes", "IFCREAL", results.throughput.maxWait], ["FootprintSquareMetres", "IFCREAL", results.cost.footprint],
      ["CapitalCostUSD", "IFCREAL", results.cost.capitalCost], ["AnnualCostUSD", "IFCREAL", results.cost.annualTCO]]);
    psetFor.forEach(function (x) { pset(x.of, x.name, x.props); });

    const stamp = (meta.timestamp || new Date().toISOString()).slice(0, 19);
    return ["ISO-10303-21;", "HEADER;",
      "FILE_DESCRIPTION(('ViewDefinition [ReferenceView_V1.2]'),'2;1');",
      "FILE_NAME(" + str((meta.fileName || "warehouse.ifc")) + "," + str(stamp) + ",('kathuman'),('Warehouse Model'),'Warehouse Model " + (meta.version || "") + "','Warehouse Model','');",
      "FILE_SCHEMA(('IFC4'));", "ENDSEC;", "DATA;"].concat(lines).concat(["ENDSEC;", "END-ISO-10303-21;"]).join("\n") + "\n";
  }

  // ------------------------------------------------------------------ DXF (R12)
  function toDXF(p, results) {
    const L = results.layout, D = calc.doorSets(p), WT = p.wall_thickness / 1000, WL = p.warehouse_length, WW = p.warehouse_width;
    const out = [];
    const g = function (code, v) { out.push(String(code), String(v)); };
    const LAYERS = [["A-WALL", 7], ["A-RACK", 30], ["A-AISLE", 4], ["A-DOCK", 3], ["A-ZONE", 40], ["A-ANNO", 2]];
    const f = function (v) { return (+v).toFixed(4); };
    g(0, "SECTION"); g(2, "HEADER"); g(9, "$ACADVER"); g(1, "AC1009"); g(9, "$EXTMIN"); g(10, f(-WT - 20)); g(20, f(-WT - 20)); g(9, "$EXTMAX"); g(10, f(WL + WT + 20)); g(20, f(WW + WT + 20)); g(0, "ENDSEC");
    g(0, "SECTION"); g(2, "TABLES"); g(0, "TABLE"); g(2, "LAYER"); g(70, LAYERS.length);
    LAYERS.forEach(function (l) { g(0, "LAYER"); g(2, l[0]); g(70, 0); g(62, l[1]); g(6, "CONTINUOUS"); });
    g(0, "ENDTAB"); g(0, "ENDSEC");
    g(0, "SECTION"); g(2, "ENTITIES");
    const line = function (layer, x1, y1, x2, y2) { g(0, "LINE"); g(8, layer); g(10, f(x1)); g(20, f(y1)); g(30, "0.0"); g(11, f(x2)); g(21, f(y2)); g(31, "0.0"); };
    const rect = function (layer, x, y, w, d) { line(layer, x, y, x + w, y); line(layer, x + w, y, x + w, y + d); line(layer, x + w, y + d, x, y + d); line(layer, x, y + d, x, y); };
    const text = function (x, y, h, s, rot) { g(0, "TEXT"); g(8, "A-ANNO"); g(10, f(x)); g(20, f(y)); g(30, "0.0"); g(40, f(h)); g(1, s); if (rot) g(50, f(rot)); };
    rect("A-WALL", -WT, -WT, WL + 2 * WT, WW + 2 * WT);
    rect("A-WALL", 0, 0, WL, WW);
    rect("A-ZONE", 0, 0, p.cross_aisle_width, WW);
    rect("A-ZONE", WL - p.cross_aisle_width, 0, p.cross_aisle_width, WW);
    for (let k = 0; k + 1 < L.segments.length; k++) rect("A-ZONE", L.segments[k].x0 + L.segmentLength, 0, p.mid_cross_aisle_width, WW);
    const segs = L.segments.filter(function (sg) { return sg.bays > 0; });
    L.rows.forEach(function (row) {
      segs.forEach(function (sg) {
        rect("A-RACK", sg.x0, row.y, sg.length, row.depth);
        for (let b = 1; b < sg.bays; b++) line("A-RACK", sg.x0 + b * p.bay_width, row.y, sg.x0 + b * p.bay_width, row.y + row.depth);
      });
      text(p.cross_aisle_width + 0.5, row.y + row.depth / 2 - 0.2, 0.4, "R" + row.index);
    });
    L.aisles.forEach(function (a) { segs.forEach(function (sg) { line("A-AISLE", sg.x0, a.y, sg.x0 + sg.length, a.y); }); });
    const doors = function (ys, x, label) { ys.forEach(function (y, i) { rect("A-DOCK", x - 0.15, y - (p.dock_bay_width - 0.7) / 2, 0.3, p.dock_bay_width - 0.7); text(x + (x > 0 ? 1 : -4), y, 0.5, label + (i + 1)); }); };
    doors(D.inY, 0, "IN");
    doors(D.outY, D.u ? 0 : WL, "OUT");
    text(0, -WT - 3, 1.2, "WAREHOUSE MODEL - " + L.numRackRows + " ROWS, " + L.baysPerRow + " BAYS/ROW, " + results.capacity.storageCapacity + " POSITIONS, " + L.rackType.label.toUpperCase());
    text(0, -WT - 5, 0.8, "INSIDE " + WL + " x " + WW + " M, CLEAR HEIGHT " + p.clear_height + " M, UNITS: METRES");
    g(0, "ENDSEC"); g(0, "EOF");
    return out.join("\r\n") + "\r\n";
  }

  // ------------------------------------------------------------------ FreeCAD
  function freecadCommand(p, defaults) {
    const sets = Object.keys(p).filter(function (k) { return defaults[k] !== undefined && p[k] !== defaults[k]; })
      .map(function (k) { return "--set " + k + "=" + p[k]; });
    return "freecadcmd freecad/create_model.py" + (sets.length ? " " + sets.join(" ") : "");
  }

  return { toIFC, toDXF, freecadCommand, ifcGuid };
});
